apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name | dump}}
  description: ${{values.description | dump}}
  annotations:
    github.com/project-slug: ${{"Jimdo / " values.name | dump}}
    backstage.io/techdocs-ref: dir:docs
spec:
  type: cli
  lifecycle: staging
  owner: ${{values.owner | dump}}
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: rust-cli-workspace-template
spec:
  type: url
  targets:
    - http://github.com/Jimdo/rust-cli-workspace-template
