apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name | dump}}
  description: ${{values.description | dump}}
  annotations:
    github.com/project-slug: ${{"Jimdo / " values.name | dump}}
    backstage.io/techdocs-ref: dir:docs
spec:
  type: cli
  lifecycle: staging
  owner: ${{values.owner | dump}}
