on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
name: Push checks
jobs:
  rust_build_and_test:
    runs-on: jimdex-default-runners
    env:
      RUSTC_WRAPPER: "sccache"
      SCCACHE_REDIS: redis://default-prod-sccache.jimdex.net:6379
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
      - name: Run tests
        run: cargo test --verbose
      - name: Build
        run: cargo build --release --all-features
